### ISSUE TITLE
Mixin Startup Crash on Server

### ISSUE THREAD

**Issue by OneWorldStudio** [sleepingdragoninn/surveyor#27] opened 2024-06-26 04:12 UTC
https://mclo.gs/veCBKHf

**Comment by sleepingdragoninn** [comment] 2024-06-26 04:14
does this occur on a fresh instance with only atlas, connector, and ffapi?

**Comment by OneWorldStudio** [comment] 2024-06-26 04:15
Yeah

**Comment by sleepingdragoninn** [comment] 2024-06-26 04:19
can you post that log as well? Sounds like a new connector-introduced issue.

**Comment by sleepingdragoninn** [comment] 2024-06-26 07:07
https://mclo.gs/u1ZWIib can't reproduce - try using the recommended 47.1.3 forge version.

**Comment by OneWorldStudio** [comment] 2024-06-26 08:40
It is not possible to run the server on 47.1.3, I have a hybrid kernel and supports only 47.3.1 and above, and besides, I have epic fight, which does not support below 47.2.0

**Comment by sleepingdragoninn** [comment] 2024-06-27 04:37
Forge versions rewrite the code the mod is running on - having a version that works on 47.1.3 and 47.3.1 is like having a version that runs on 1.19.2 and 1.20.1 - possible, but by no means a guarantee, and usually impossible to fix if it breaks.

That said, here's atlas running on neo 47.1.106 (latest neo for 1.20.1) - try that?

![image](https://github.com/sisby-folk/surveyor/assets/55819817/bb5b8bad-ebd5-4bd9-95ec-402038e2784d)

**Comment by OneWorldStudio** [comment] 2024-06-29 02:54
> Версии Forge переписывают код, на котором работает мод - иметь версию, работающую на 47.1.3 и 47.3.1, это все равно, что иметь версию, работающую на 1.19.2 и 1.20.1 - возможно, но ни в коем случае не гарантия, и обычно невозможно починить, если он сломается.
> 
> Тем не менее, вот Atlas, работающий на Neo 47.1.106 (последняя Neo для 1.20.1) — попробуйте его?
> 
> ![изображение](https://private-user-images.githubusercontent.com/55819817/343632159-bb5b8bad-ebd5-4bd9-95ec-402038e2784d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2Mjk5MTEsIm5iZiI6MTcxOTYyOTYxMSwicGF0aCI6Ii81NTgxOTgxNy8zNDM2MzIxNTktYmI1YjhiYWQtZWJkNS00YmQ5LTk1ZWMtNDAyMDM4ZTI3ODRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDAyNTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMTIyYjBjOTkxYjUyNzI0NWZiZTEyZTFiNWJiZDJjY2VjMjYzNjgzNjk3ZjY0Njg0ZjRiNDU1OGMyZTI4NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsauYyhy1jRBi7jSf2i2BudQmuo01enJtfvm_nQHYjA)

Okay, thank so much

**Comment by OneWorldStudio** [comment] 2024-06-29 02:56
[05:56:21 FATAL]: Mixin apply for mod surveyor failed surveyor.mixins.json:MixinServerWorld from mod surveyor -> net.minecraft.server.level.ServerLevel: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onPointOfInterestRemoved could not find any targets matching 'Lnet/minecraft/server/level/ServerLevel;m_207559_(Lnet/minecraft/core/BlockPos;)V' in net.minecraft.server.level.ServerLevel. Using refmap surveyor-refmap.json [PREINJECT Applicator Phase -> surveyor.mixins.json:MixinServerWorld from mod surveyor -> Prepare Injections ->  -> handler$zck000$surveyor$onPointOfInterestRemoved(Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

**Comment by OneWorldStudio** [comment] 2024-06-29 02:58
He generally complains to me about surveyor, not Atlas, although what's wrong with it without crash

**Comment by OneWorldStudio** [comment] 2024-06-29 03:01
It doesn't work only on the server side, but everything works fine on the Client before that.

**Comment by sleepingdragoninn** [comment] 2024-06-30 06:27
still can't reproduce (latest neo, server) https://mclo.gs/UdZx0bt

**Comment by Xiaoanawa** [comment] 2024-07-01 00:33
I encountered the same issue with version 1.20.1, using Mohist as the server core, which is a hybrid platform combining Forge with Bukkit and Spigot, specifically running Forge version 47.3.1. The Atlas mod was version 2.9.5, and Surveyor was version 0.5.6 (previously, I had Atlas at 2.9.5 and Surveyor at 0.5.3, and the server still wouldn't start before the update).

Neither mod, whether installed individually or together, would allow the server to start up. There was no crash log, and the log content is the same https://mclo.gs/QAQI8Nq

However, when using a Forge server alone, I was able to successfully start it, Forge version 47.2.36.  

I attempted to launch the server with Mohist server core using Forge 47.2.32, but it still failed to start.  https://mclo.gs/MaSewNP

I intended to test with the Mohist server core paired with Forge version 47.1.3, but network issues prevented me from downloading it. https://mclo.gs/VbNUxDv

**Comment by sleepingdragoninn** [comment] 2024-07-01 00:52
no plans to support a bukkit/spigot hybrid server, whether through something like mohist or cardboard

**Comment by sleepingdragoninn** [comment] 2024-07-01 00:53
@OneWorldStudio let me know if you end up with the crash on actual forge again (latest neo or recommended), and post the log - I'm closing this for now because I still have no repro case after many attempts and it's going off topic.

**Closed as not planned by sleepingdragoninn** 2024-07-01 00:52 UTC
Labels: incompatibility

**Comment by Xiaoanawa** [comment] 2024-07-01 01:08
Okay... thanks for your answer.
