### ISSUE TITLE
Crash during exploration

### ISSUE THREAD

**Issue by CheshireSwift** [sleepingdragoninn/surveyor#51] opened 2024-09-09 16:53 UTC
Got a hard crash when exploring the world (index out of bounds). Disabling Antique Atlas moved it to hard crash from Surveyor complaining about a null return from landmarks.

Disabling Surveyor and Surveystones allowed the game to run.

I explored a bit further in the same direction (to try generating chunks), then re-enabled the mods. Crash again.

Crash with all enabled (Surveyor, AA, Surveystones) - happens on loading into the world.

[redacted] 

Crash with AA disabled - likewise happens on world load.

[redacted] 

With Surveyor + AA but no Surveystones, mod loading hangs at "constructing", never makes it to the main menu.

Disabling all three once again allows the game to run.

**Comment by sleepingdragoninn** [comment] 2024-09-09 17:06
raw logs can contain personal information - prism has a built in button to upload to mclo.gs instead.

https://mclo.gs/IjXsm6b

https://mclo.gs/YAPP9Oq

first crash resembles #46 (was a mod uninstalled? it's hard to nail the root causes of palette OOB errors), second crash is a genuinely serious bug with Surveystones where's its both A) not requesting the landmark system to be turned on properly and B) not safe when the landmark system is disabled - can you file that there?

**Comment by CheshireSwift** [comment] 2024-09-09 19:37
1) Possibly. The game was launched with some that I then removed. I think I removed them before creating the world, but I'm not 100% certain.
2) Can do 👍

**Comment by sleepingdragoninn** [comment] 2024-09-18 07:54
closing as a duplicate of #46

**Closed as not planned by sleepingdragoninn** 2024-09-18 07:54 UTC
