### ISSUE TITLE
Anytime a player joins an Error appears

### ISSUE THREAD

**Issue by AnastasiosMadSwaggin** [sleepingdragoninn/surveyor#42] opened 2024-07-19 22:24 UTC
Whenever a player joins, the console displays the message: "[Server thread/ERROR]: Error executing task on Server." Additionally, waypoints, waypoint names, and exploration progress disappear randomly. I configured the mod to sync everything globally, which might be related to the issue.

I tested if any of the other mods on my server were causing the problem by removing them, but it seems that even when only Surveyor and Fabric API are installed, the problems still occur.

[latest.log](https://github.com/user-attachments/files/16317439/latest.log)

**Comment by sleepingdragoninn** [comment] 2024-07-22 00:45
Looks like your structure save files are bad - they have a null in a non-nullable field such as structure type.
Did you previously have ChoiceTheorem's Overhauled Villages installed?

I'll try find a way for this to self-correct on load.

**Comment by AnastasiosMadSwaggin** [comment] 2024-07-22 09:29
I didn't add any structure mod prior to this happening. Some of the other mods I used might be the problem, but I'm not sure which mod is the culprit. Here’s a picture of all the mods for reference:
![image](https://github.com/user-attachments/assets/cb4a22b5-0702-4b94-baa2-39486ffc7855)

**Comment by AnastasiosMadSwaggin** [comment] 2024-07-30 15:53
Still happening in the newest version

**Comment by sleepingdragoninn** [comment] 2024-07-31 09:23
can you send a copy of your server's structures save file, stored in `world/data/surveyor`?

the server is attempting to sync structure data to players on-join which is what appears to be failing due to a null value. Can't reproduce this with vanilla, may be some kind of issue with an uninstalled mod or a datapack.

**Comment by AnastasiosMadSwaggin** [comment] 2024-07-31 12:12
apparently my structure saves are too big to be uploaded here directly so i uploaded it on wetransfer if you have another file hoster you feel more comfortable with i will upload it there
https://we.tl/t-LaTHb5colY

**Comment by sleepingdragoninn** [comment] 2024-07-31 12:24
Yep, so i've had a further look and I think we've just resolved this issue in surveyor 0.6.18 - could you add that and try?

**Comment by AnastasiosMadSwaggin** [comment] 2024-07-31 12:28
i might be blind but i cant seem to find 0.6.18 for 1.21 on modrinth or on github just the 1.20 version

**Comment by sleepingdragoninn** [comment] 2024-07-31 12:39
hilariously i did not hit the button - it's up now

**Comment by AnastasiosMadSwaggin** [comment] 2024-07-31 12:43
seems like its fixed thank you

**Comment by AnastasiosMadSwaggin** [comment] 2024-07-31 12:43
The error still appears

[12:42:30] [Server thread/INFO]: _Anastasios_ joined the game
[12:42:33] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2030ms or 40 ticks behind
[12:42:37] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.AbstractMultimap.putAll(AbstractMultimap.java:83) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.HashMultimap.putAll(HashMultimap.java:52) ~[guava-32.1.2-jre.jar:?]
	at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at folk.sisby.surveyor.util.MapUtil.asMultiMap(MapUtil.java:17) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.packet.S2CStructuresAddedPacket.toPayloads(S2CStructuresAddedPacket.java:67) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:17) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:26) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.SurveyorNetworking.handleKnownStructures(SurveyorNetworking.java:83) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.SurveyorNetworking.handleServer(SurveyorNetworking.java:112) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.SurveyorNetworking.lambda$init$2(SurveyorNetworking.java:52) ~[surveyor-0.6.18+1.21.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.lambda$receive$0(ServerPlayNetworkAddon.java:72) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-e118cdd1d6eac366.jar:?]
	at MC/net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:814) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[12:42:38] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.AbstractMultimap.putAll(AbstractMultimap.java:83) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.HashMultimap.putAll(HashMultimap.java:52) ~[guava-32.1.2-jre.jar:?]
	at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at folk.sisby.surveyor.util.MapUtil.asMultiMap(MapUtil.java:17) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.packet.S2CStructuresAddedPacket.toPayloads(S2CStructuresAddedPacket.java:67) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:17) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:26) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.SurveyorNetworking.handleKnownStructures(SurveyorNetworking.java:83) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.SurveyorNetworking.handleServer(SurveyorNetworking.java:112) ~[surveyor-0.6.18+1.21.jar:?]
	at folk.sisby.surveyor.SurveyorNetworking.lambda$init$2(SurveyorNetworking.java:52) ~[surveyor-0.6.18+1.21.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.lambda$receive$0(ServerPlayNetworkAddon.java:72) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-e118cdd1d6eac366.jar:?]
	at MC/net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:814) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by sleepingdragoninn** [comment] 2024-07-31 12:47
Ah alright, looks like you have a very similar looking but not identical issue related to tags - I'll do up a fix.

**Comment by sleepingdragoninn** [comment] 2024-07-31 12:50
Try out 0.6.19, I've taken a shot in the dark because I don't have your particular setup, but I think it covers off the special case you're experiencing.

**Comment by AnastasiosMadSwaggin** [comment] 2024-07-31 12:56
there is no 1.21 again lol

**Comment by sleepingdragoninn** [comment] 2024-07-31 12:59
fixed :joy:

**Comment by AnastasiosMadSwaggin** [comment] 2024-07-31 13:02
looks fixed thank you

**Comment by sleepingdragoninn** [comment] 2024-07-31 13:04
Thanks for the prompt responses! closing this

**Closed as completed by sleepingdragoninn** 2024-07-31 13:04 UTC
Labels: bug, incompatibility
