### ISSUE TITLE
Crash when connecting to server where surveyor data is shared with somone

### ISSUE THREAD

**Issue by Racooder** [sleepingdragoninn/surveyor#17] opened 2024-04-29 17:13 UTC
When sharing surveyor data with a friend via `/surveyor share <player>` the game crashes for one of the accepting player and he can't join the server until deleting the `data/surveyor` folder on the client and server side.

[crash-report.txt](https://github.com/sisby-folk/surveyor/files/15152473/crash-2024-04-29_19.05.12-client.txt)
[log.txt](https://github.com/sisby-folk/surveyor/files/15152474/2024-04-29-3.log)

**Comment by iacuobos** [comment] 2024-04-29 17:25
Duplicate of #16 
Updating seemingly fixes the crash (you're using a old surveyor version), but I was about to report another problem when joining the server.
![image](https://github.com/sisby-folk/surveyor/assets/42287552/d0e7bd18-2e97-44fd-816b-2345106084c0)

**Comment by iacuobos** [comment] 2024-05-01 02:52
> java.io.EOFException: Unexpected end of ZLIB input stream
> 	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
> 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
> 	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
> 	at net.minecraft.class_6826.method_39780(class_6826.java:94)
> 	at net.minecraft.class_6826.read(class_6826.java:47)
> 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
> 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
> 	at net.minecraft.class_2479$1.method_23232(class_2479.java:27)
> 	at net.minecraft.class_2479$1.method_23262(class_2479.java:20)
> 	at net.minecraft.class_2487.method_10581(class_2487.java:500)
> 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
> 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
> 	at net.minecraft.class_2487.method_10581(class_2487.java:500)
> 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
> 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
> 	at net.minecraft.class_2487.method_10581(class_2487.java:500)
> 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
> 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
> 	at net.minecraft.class_2487.method_10581(class_2487.java:500)
> 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
> 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
> 	at net.minecraft.class_2487.method_10581(class_2487.java:500)
> 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
> 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
> 	at net.minecraft.class_2507.method_10626(class_2507.java:147)
> 	at net.minecraft.class_2507.method_10625(class_2507.java:91)
> 	at net.minecraft.class_2507.method_10629(class_2507.java:36)
> 	at net.minecraft.class_2507.method_30613(class_2507.java:26)
> 	at folk.sisby.surveyor.terrain.WorldTerrainSummary.load(WorldTerrainSummary.java:129)
> 	at folk.sisby.surveyor.WorldSummary.load(WorldSummary.java:18)
> 	at net.minecraft.class_3218.handler$idc001$surveyor$loadSummary(class_3218.java:15232)
> 	at net.minecraft.class_3218.<init>(class_3218.java:224)
> 	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:359)
> 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:324)
> 	at net.minecraft.class_1132.method_3823(class_1132.java:69)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
> 	at java.base/java.lang.Thread.run(Thread.java:833)

Was able to reproduce it partially, not sure if it's the same issue

**Comment by sleepingdragoninn** [comment] 2024-05-01 04:17
feel free to refile any reproduceable issues on latest surveyor with your latest.log posted to `https://mclo.gs/`

**Closed as not planned** 2024-05-01 04:18 UTC
